# Generated by Django 5.1.3 on 2024-11-21 11:55

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Никнейм пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(error_messages={'unique': 'A user with that user_id already exists.'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')]),
        ),
    ]
